<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="PDFsharp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenCampus.Sis.Application\OpenCampus.Sis.Application.csproj" />
  </ItemGroup>

</Project>
