using OpenCampus.Sis.Domain.Enrolments;

namespace OpenCampus.Sis.Application.Certificates;

/// <summary>Persistence contract for certificates (LR-03); the aggregate is the enrolment (13.3: Enrolment 1—1 Certificate).</summary>
public interface ICertificateRepository
{
    Task<Certificate?> FindByIdAsync(Guid id, CancellationToken cancellationToken);

    /// <summary>The certificate of the enrolment, if one has been issued (BR-11 check).</summary>
    Task<Certificate?> FindByEnrolmentAsync(Guid enrolmentId, CancellationToken cancellationToken);

    /// <summary>Exact match on the unique verification code (13.3), for anonymous verification.</summary>
    Task<Certificate?> FindByVerificationCodeAsync(string verificationCode, CancellationToken cancellationToken);

    /// <summary>Every certificate of a learner across enrolments, newest first (one join, NFR-04).</summary>
    Task<IReadOnlyList<Certificate>> ListByLearnerAsync(Guid learnerId, CancellationToken cancellationToken);

    void Add(Certificate certificate);
}

/// <summary>
/// SDD 18.5 storage abstraction for certificate documents, declared in the SIS application layer so the physical
/// mechanism is replaceable without change to consuming code. Names are generated by the implementation (SEC-23);
/// files are retrieved only through <see cref="OpenReadAsync"/> behind an authorised endpoint (SEC-24/25).
/// </summary>
public interface ICertificateStore
{
    /// <summary>Writes the document beneath <paramref name="relativeDirectory"/> (derived by the caller from the owning identifiers) and returns the relative path.</summary>
    Task<string> SaveAsync(string relativeDirectory, ReadOnlyMemory<byte> content, CancellationToken cancellationToken);

    /// <summary>A readable stream for a stored document, or null when it is absent.</summary>
    Task<Stream?> OpenReadAsync(string relativePath, CancellationToken cancellationToken);

    /// <summary>Removes a stored document; absence is not an error.</summary>
    Task DeleteAsync(string relativePath, CancellationToken cancellationToken);
}

/// <summary>Everything printed on a certificate. Built by the application layer; rendered by infrastructure (8.1: no infrastructure type in this signature).</summary>
public sealed record CertificateDocument(
    string VerificationCode,
    DateTime IssuedAtUtc,
    string LearnerFullNameEn,
    string LearnerFullNameAr,
    string LearnerNumber,
    string ProgrammeCode,
    string ProgrammeNameEn,
    string CourseCode,
    string CourseNameEn,
    string SectionCode,
    string Term,
    DateTime CompletedAtUtc,
    decimal FinalGradePercent);

/// <summary>Renders a certificate document to PDF bytes. The library behind it is selected in infrastructure (section 7: PDF generation).</summary>
public interface ICertificateDocumentRenderer
{
    byte[] Render(CertificateDocument document);
}

/// <summary>Produces the unpredictable verification code printed on a certificate (13.3 unique VerificationCode).</summary>
public interface IVerificationCodeGenerator
{
    string Next();
}
