using System.Text.Json;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using OpenCampus.SharedKernel;
using OpenCampus.Sis.Application.Abstractions;
using OpenCampus.Sis.Application.External;
using OpenCampus.Sis.Application.Grading;
using OpenCampus.Sis.Domain.Courses;
using OpenCampus.Sis.Domain.Enrolments;
using OpenCampus.Sis.Domain.Learners;
using OpenCampus.Sis.Domain.Programmes;
using OpenCampus.Sis.Domain.Sections;

namespace OpenCampus.Sis.Application.Certificates;

/// <summary>
/// Certificate issuance, listing, download and anonymous verification (15.3 "Certification"). BR-10 and BR-11 are
/// decided by <see cref="Certificate.Issue"/>; the pass threshold comes from Appendix B "Academic". The document is
/// rendered and stored (18.5) before the row is committed, and removed again if the commit fails, so no certificate
/// row can exist without its file. Every issuance is written to the audit trail (SEC-30) through the Identity
/// contract. Scope (SEC-12): a learner reaches only their own certificates; administrative reach requires
/// <see cref="LearnerAdministration"/>; anything else is answered "not found" (API-06).
/// </summary>
public sealed class CertificateService(
    ICertificateRepository certificates,
    IEnrolmentRepository enrolments,
    ILearnerRepository learners,
    ISectionRepository sections,
    ICourseRepository courses,
    IProgrammeRepository programmes,
    IUserDirectory users,
    ICurrentUser currentUser,
    IAuditTrail audit,
    LearnerNotifier notifier,
    IRecordsArchive archive,
    ILogger<CertificateService> logger,
    ICertificateStore store,
    ICertificateDocumentRenderer renderer,
    IVerificationCodeGenerator codes,
    IOptions<AcademicOptions> academic,
    ISisUnitOfWork unitOfWork,
    TimeProvider clock)
{
    /// <summary>The Appendix C capability that confers reach over any learner's certificates, alongside the learner's own.</summary>
    public const string LearnerAdministration = "sis.learner.read";

    public const string ContentType = "application/pdf";

    /// <summary>Issues the certificate of a completed enrolment (BR-10/BR-11 in the aggregate); SEC-30 audit.</summary>
    public async Task<Result<CertificateResponse>> IssueAsync(Guid enrolmentId, CancellationToken cancellationToken)
    {
        var enrolment = await enrolments.FindByIdAsync(enrolmentId, cancellationToken);
        if (enrolment is null)
        {
            return Result.Failure<CertificateResponse>(SisErrors.EnrolmentNotFound);
        }

        var alreadyIssued = await certificates.FindByEnrolmentAsync(enrolment.Id, cancellationToken) is not null;
        // BR-11 then BR-10, decided by the aggregate before anything is rendered or persisted.
        Certificate.EnsureIssuable(enrolment, academic.Value.PassThresholdPercent, alreadyIssued);

        var (learner, user, section, course, programme) = (await LoadContextAsync([enrolment], cancellationToken))[enrolment.Id];
        var now = clock.GetUtcNow().UtcDateTime;
        var code = await UnusedCodeAsync(cancellationToken);

        var document = new CertificateDocument(
            code, now,
            user?.FullNameEn ?? learner.LearnerNumber, user?.FullNameAr ?? learner.LearnerNumber, learner.LearnerNumber,
            programme.Code, programme.NameEn, course.Code, course.NameEn, section.Code, section.TermName,
            enrolment.CompletedAtUtc!.Value, enrolment.FinalGrade!.Value);

        // 18.5: layout derived from the owning identifiers; the stored name is generated by the store (SEC-23).
        var relativePath = await store.SaveAsync($"certificates/{learner.Id:N}/{enrolment.Id:N}", renderer.Render(document), cancellationToken);
        var certificate = Certificate.Issue(enrolment, academic.Value.PassThresholdPercent, alreadyIssued, code, relativePath, now);

        try
        {
            certificates.Add(certificate);
            await unitOfWork.SaveChangesAsync(cancellationToken);
        }
        catch
        {
            await store.DeleteAsync(relativePath, CancellationToken.None);
            throw;
        }

        await audit.RecordAsync(
            SisAuditEventTypes.CertificateIssued, nameof(Certificate), certificate.Id,
            JsonSerializer.Serialize(new { enrolmentId = enrolment.Id, learnerId = learner.Id, sectionId = section.Id, finalGrade = enrolment.FinalGrade, verificationCode = code }),
            cancellationToken);

        var response = ToResponse(certificate, enrolment, learner, user, section, course, programme);

        // EXT-05: the institutional record of the award; EXT-01: the learner is told. Both are side effects of a committed
        // issuance — their outcome is logged and never reverses it.
        var archived = await archive.ArchiveAsync(new ArchiveRecord("certificate", certificate.Id, JsonSerializer.Serialize(response)), cancellationToken);
        if (archived.Outcome != ExternalOutcome.Succeeded)
        {
            logger.LogWarning("Certificate {CertificateId} was not archived: {Reasons}", certificate.Id, string.Join("; ", archived.Failures.Select(f => f.Reason)));
        }

        await notifier.CertificateIssuedAsync(learner, course.Code, course.NameEn, code, cancellationToken);

        return Result.Success(response);
    }

    /// <summary>One certificate by identifier: its learner, or a holder of learner administration; otherwise not found.</summary>
    public async Task<Result<CertificateResponse>> GetAsync(Guid certificateId, CancellationToken cancellationToken)
    {
        var certificate = await FindReachableAsync(certificateId, cancellationToken);
        if (certificate is null)
        {
            return Result.Failure<CertificateResponse>(SisErrors.CertificateNotFound);
        }

        return Result.Success((await ToResponsesAsync([certificate], cancellationToken))[0]);
    }

    /// <summary>The certificate of an enrolment, for administrative enrolment views; not found when none has been issued.</summary>
    public async Task<Result<CertificateResponse>> GetForEnrolmentAsync(Guid enrolmentId, CancellationToken cancellationToken)
    {
        if (!currentUser.HasPermission(LearnerAdministration))
        {
            return Result.Failure<CertificateResponse>(SisErrors.CertificateNotFound);
        }

        var certificate = await certificates.FindByEnrolmentAsync(enrolmentId, cancellationToken);
        return certificate is null
            ? Result.Failure<CertificateResponse>(SisErrors.CertificateNotFound)
            : Result.Success((await ToResponsesAsync([certificate], cancellationToken))[0]);
    }

    /// <summary>Certificate listing for the calling learner (15.3), newest first.</summary>
    public async Task<Result<IReadOnlyList<CertificateResponse>>> ListMineAsync(CancellationToken cancellationToken)
    {
        var learner = await CurrentLearnerAsync(cancellationToken);
        if (learner is null)
        {
            return Result.Failure<IReadOnlyList<CertificateResponse>>(SisErrors.NoLearnerRecordForCaller);
        }

        var mine = await certificates.ListByLearnerAsync(learner.Id, cancellationToken);
        return Result.Success(await ToResponsesAsync(mine, cancellationToken));
    }

    /// <summary>Certificates of one learner, for administrative learner views.</summary>
    public async Task<Result<IReadOnlyList<CertificateResponse>>> ListForLearnerAsync(Guid learnerId, CancellationToken cancellationToken)
    {
        if (!currentUser.HasPermission(LearnerAdministration) || await learners.FindByIdAsync(learnerId, cancellationToken) is null)
        {
            return Result.Failure<IReadOnlyList<CertificateResponse>>(SisErrors.LearnerNotFound);
        }

        var items = await certificates.ListByLearnerAsync(learnerId, cancellationToken);
        return Result.Success(await ToResponsesAsync(items, cancellationToken));
    }

    /// <summary>Opens the document for download (SEC-25): its learner or a holder of learner administration; otherwise not found.</summary>
    public async Task<Result<CertificateDownload>> OpenAsync(Guid certificateId, CancellationToken cancellationToken)
    {
        var certificate = await FindReachableAsync(certificateId, cancellationToken);
        if (certificate is null)
        {
            return Result.Failure<CertificateDownload>(SisErrors.CertificateNotFound);
        }

        var stream = await store.OpenReadAsync(certificate.FilePath, cancellationToken);
        return stream is null
            ? Result.Failure<CertificateDownload>(SisErrors.CertificateDocumentMissing)
            : Result.Success(new CertificateDownload(stream, ContentType, $"certificate-{certificate.VerificationCode}.pdf"));
    }

    /// <summary>
    /// Anonymous verification by code (15.3, 15.4): confirms what the code certifies without exposing internal
    /// identifiers. The code is compared exactly after trimming and upper-casing so a transcribed code still matches.
    /// </summary>
    public async Task<Result<CertificateVerificationResponse>> VerifyAsync(string? verificationCode, CancellationToken cancellationToken)
    {
        var normalised = (verificationCode ?? string.Empty).Trim().ToUpperInvariant();
        if (normalised.Length == 0 || normalised.Length > Certificate.VerificationCodeMaxLength)
        {
            return Result.Failure<CertificateVerificationResponse>(SisErrors.CertificateNotFound);
        }

        var certificate = await certificates.FindByVerificationCodeAsync(normalised, cancellationToken);
        if (certificate is null)
        {
            return Result.Failure<CertificateVerificationResponse>(SisErrors.CertificateNotFound);
        }

        var r = (await ToResponsesAsync([certificate], cancellationToken))[0];
        return Result.Success(new CertificateVerificationResponse(
            r.VerificationCode, r.IssuedAtUtc, r.LearnerFullNameEn, r.LearnerFullNameAr,
            r.CourseCode, r.CourseNameEn, r.CourseNameAr, r.ProgrammeNameEn, r.ProgrammeNameAr, r.Term, r.CompletedAtUtc));
    }

    // ----- Helpers -----

    private Task<Learner?> CurrentLearnerAsync(CancellationToken cancellationToken) =>
        currentUser.UserId is { } userId ? learners.FindByUserIdAsync(userId, cancellationToken) : Task.FromResult<Learner?>(null);

    /// <summary>SEC-12: the certificate if the caller may reach it — its own learner, or an administrator of learners.</summary>
    private async Task<Certificate?> FindReachableAsync(Guid certificateId, CancellationToken cancellationToken)
    {
        var certificate = await certificates.FindByIdAsync(certificateId, cancellationToken);
        if (certificate is null)
        {
            return null;
        }

        if (currentUser.HasPermission(LearnerAdministration))
        {
            return certificate;
        }

        var learner = await CurrentLearnerAsync(cancellationToken);
        if (learner is null)
        {
            return null;
        }

        var enrolment = await enrolments.FindByIdAsync(certificate.EnrolmentId, cancellationToken);
        return enrolment?.LearnerId == learner.Id ? certificate : null;
    }

    /// <summary>A fresh code that is not yet in use; the unique index remains the final guarantee.</summary>
    private async Task<string> UnusedCodeAsync(CancellationToken cancellationToken)
    {
        for (var attempt = 0; attempt < 5; attempt++)
        {
            var code = codes.Next();
            if (await certificates.FindByVerificationCodeAsync(code, cancellationToken) is null)
            {
                return code;
            }
        }

        throw new InvalidOperationException("Could not generate an unused verification code.");
    }

    private async Task<IReadOnlyList<CertificateResponse>> ToResponsesAsync(IReadOnlyList<Certificate> items, CancellationToken cancellationToken)
    {
        if (items.Count == 0)
        {
            return [];
        }

        var enrolmentsById = new Dictionary<Guid, Enrolment>();
        foreach (var id in items.Select(c => c.EnrolmentId).Distinct())
        {
            enrolmentsById[id] = (await enrolments.FindByIdAsync(id, cancellationToken))!;
        }

        var context = await LoadContextAsync(enrolmentsById.Values, cancellationToken);
        return items.Select(c =>
        {
            var enrolment = enrolmentsById[c.EnrolmentId];
            var (learner, user, section, course, programme) = context[enrolment.Id];
            return ToResponse(c, enrolment, learner, user, section, course, programme);
        }).ToList();
    }

    /// <summary>Batched resolution of everything a certificate names (NFR-04): one lookup per entity type, not per row.</summary>
    private async Task<IReadOnlyDictionary<Guid, (Learner, UserSummary?, CourseSection, Course, Programme)>> LoadContextAsync(
        IReadOnlyCollection<Enrolment> items, CancellationToken cancellationToken)
    {
        var learnersById = await learners.FindManyAsync(items.Select(e => e.LearnerId), cancellationToken);
        var usersById = await users.FindManyAsync(learnersById.Values.Select(l => l.UserId), cancellationToken);
        var sectionsById = await sections.FindManyAsync(items.Select(e => e.SectionId), cancellationToken);
        var coursesById = await courses.FindManyAsync(sectionsById.Values.Select(s => s.CourseId), cancellationToken);
        var programmesById = await programmes.FindManyAsync(coursesById.Values.Select(c => c.ProgrammeId), cancellationToken);

        return items.ToDictionary(e => e.Id, e =>
        {
            var learner = learnersById[e.LearnerId];
            var section = sectionsById[e.SectionId];
            var course = coursesById[section.CourseId];
            return (learner, usersById.GetValueOrDefault(learner.UserId), section, course, programmesById[course.ProgrammeId]);
        });
    }

    private static CertificateResponse ToResponse(Certificate c, Enrolment e, Learner learner, UserSummary? user, CourseSection section, Course course, Programme programme) =>
        new(
            c.Id, e.Id, learner.Id, learner.LearnerNumber,
            user?.FullNameEn ?? learner.LearnerNumber, user?.FullNameAr ?? learner.LearnerNumber,
            section.Id, section.Code, section.TermName,
            course.Code, course.NameEn, course.NameAr,
            programme.Code, programme.NameEn, programme.NameAr,
            e.FinalGrade ?? 0m, e.CompletedAtUtc ?? c.IssuedAtUtc,
            c.VerificationCode, c.IssuedAtUtc);
}
