<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Shouldly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Identity\OpenCampus.Identity.Domain\OpenCampus.Identity.Domain.csproj" />
    <ProjectReference Include="..\..\src\Identity\OpenCampus.Identity.Application\OpenCampus.Identity.Application.csproj" />
    <ProjectReference Include="..\..\src\Sis\OpenCampus.Sis.Domain\OpenCampus.Sis.Domain.csproj" />
    <ProjectReference Include="..\..\src\Sis\OpenCampus.Sis.Application\OpenCampus.Sis.Application.csproj" />
    <ProjectReference Include="..\..\src\Lms\OpenCampus.Lms.Domain\OpenCampus.Lms.Domain.csproj" />
    <ProjectReference Include="..\..\src\Lms\OpenCampus.Lms.Application\OpenCampus.Lms.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Using Include="Shouldly" />
  </ItemGroup>

</Project>
